OpenZeppelin/openzeppelin-upgrades

README.md
packages/plugin-truffle/src/validate.ts

Fixes #124.
~Not adding a link in the error because we've freezed the code before the announcement.~

Explain Truffle full recompilation requirement

---

CHANGELOG.md
packages/plugin-truffle/src/deploy-proxy.ts
packages/plugin-truffle/test/test/happy-path.js

Analogous to #129 but for Truffle.

Store transaction hash in Truffle contract instance

---

README.md

Rearrange content in main readme

---

CHANGELOG.md
packages/core/package.json
packages/plugin-buidler/package.json
packages/plugin-truffle/package.json

Fixes #145.
Additionally improves debugging experience by allowing TS users to jump to the definition of plugin functions.

Add src directory to npm packages

---

packages/core/src/scripts/migrate-oz-cli-project.test.ts
packages/core/src/scripts/migrate-oz-cli-project.ts

Fixes https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/192

Support CLI manifests with zosversion field

---

docs/modules/ROOT/pages/buidler-upgrades.adoc
docs/modules/ROOT/pages/truffle-upgrades.adoc

Add Tip to Using with Truffle/Buidler introduction linking to step by step guides

Add links to step by step guides

---

docs/modules/ROOT/pages/api-buidler-upgrades.adoc
docs/modules/ROOT/pages/api-truffle-upgrades.adoc
packages/plugin-buidler/src/deploy-proxy.ts
packages/plugin-truffle/CHANGELOG.md
packages/plugin-truffle/src/deploy-proxy.ts

Allow disabling proxy initialization

---

packages/plugin-truffle/CHANGELOG.md
packages/plugin-truffle/package.json
packages/plugin-truffle/src/validate.ts
packages/plugin-truffle/test/package.json

Fix spurious Truffle error on Windows

---

packages/core/ava.config.js
packages/core/hardhat.config.js
packages/core/package.json
packages/plugin-hardhat/ava.config.js
packages/plugin-hardhat/hardhat.config.js
packages/plugin-hardhat/package.json
packages/plugin-hardhat/test/multi-compiler.js
yarn.lock

Remove ts-node

---

packages/plugin-hardhat/CHANGELOG.md
packages/plugin-hardhat/src/index.ts
packages/plugin-hardhat/src/utils/is-full-solc-output.ts

Check solc output is complete before validations

---

packages/core/CHANGELOG.md
packages/core/src/deployment.ts

Reported in the forum: [Invalid deployment using Infura](https://forum.openzeppelin.com/t/invalid-deployment-using-infura/5371/5).

Fix InvalidDeployment error on some networks

---

packages/core/src/scripts/migrate-oz-cli-project.ts
packages/core/src/storage/index.ts
packages/core/src/utils/log.ts
packages/plugin-hardhat/src/admin.ts
packages/plugin-truffle/src/admin.ts

Keyword has been removed. Need to use direct way.
https://github.com/chalk/chalk/issues/431

Remove use of chalk.keyword

---

README.md

Fixed typo in the link to the Hardhat scripts documentation.

Fix link to Hardhat scripts doc

---

docs/modules/ROOT/pages/proxies.adoc

- Changed `it's` to `its`
- Changed `ie` to `i.e.,`

Fix grammar in proxies doc

---

docs/modules/ROOT/pages/api-hardhat-upgrades.adoc
docs/modules/ROOT/pages/api-truffle-upgrades.adoc
docs/modules/ROOT/pages/index.adoc

Change references in the docs to `admin.changeAdminForProxy` into `admin.changeProxyAdmin`.

Fix incorrect docs for upgrades.admin.changeProxyAdmin

---

docs/modules/ROOT/pages/hardhat-upgrades.adoc
docs/modules/ROOT/pages/index.adoc
docs/modules/ROOT/pages/truffle-upgrades.adoc

Related to #342 
Depends on #491
Improve docs to more clearly differentiate usage for the different proxy patterns.

Improve docs for UUPS/transparent/beacon proxies

---

packages/core/src/impl-address.ts

Match less specific reverted message when testing for beacon

---

packages/core/src/storage/extract.ts

Remove use of mutating reverse on shared data

---

docs/modules/ROOT/pages/faq.adoc

Fix comparison as reported in https://forum.openzeppelin.com/t/uupsupgradable-delegatecall/23677/7

Fix comparison in OnlyDelegateCall example

---

docs/modules/ROOT/pages/api-hardhat-upgrades.adoc
packages/core/CHANGELOG.md
packages/core/src/deployment.ts
packages/core/src/impl-store.ts
packages/core/src/index.ts
packages/plugin-defender-hardhat/CHANGELOG.md
packages/plugin-defender-hardhat/src/propose-upgrade.ts
packages/plugin-defender-hardhat/test/propose-upgrade-uups.js
packages/plugin-hardhat/CHANGELOG.md
packages/plugin-hardhat/src/prepare-upgrade.ts
packages/plugin-hardhat/src/utils/deploy-impl.ts
packages/plugin-hardhat/src/utils/options.ts
packages/plugin-hardhat/test/prepare-upgrade-txresponse.js

Fixes https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/554

Return ethers transaction response with defender.proposeUpgrade

---

docs/modules/ROOT/pages/writing-upgradeable.adoc

Change example to onlyInitializing

---

docs/modules/ROOT/pages/api-hardhat-upgrades.adoc
packages/plugin-hardhat/CHANGELOG.md
packages/plugin-hardhat/src/index.ts
packages/plugin-hardhat/src/verify-proxy.ts

Override verify:verify subtask from hardhat-etherscan

---

docs/modules/ROOT/pages/faq.adoc

Fixes https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/718

Add docs for allow-reachable

---

packages/core/CHANGELOG.md
packages/core/src/provider.ts

Add sepolia testnet in networkNames

---

docs/modules/ROOT/pages/api-hardhat-upgrades.adoc
docs/modules/ROOT/pages/api-truffle-upgrades.adoc
packages/core/CHANGELOG.md
packages/core/src/index.ts
packages/core/src/usage-error.ts
packages/plugin-hardhat/CHANGELOG.md
packages/plugin-hardhat/src/deploy-implementation.ts
packages/plugin-hardhat/src/prepare-upgrade.ts
packages/plugin-hardhat/src/utils/deploy-impl.ts
packages/plugin-hardhat/test/beacon-upgrade-block-proxy.js
packages/plugin-hardhat/test/implementation-functions.js
packages/plugin-truffle/CHANGELOG.md
packages/plugin-truffle/src/deploy-implementation.ts
packages/plugin-truffle/src/prepare-upgrade.ts
packages/plugin-truffle/src/utils/deploy-impl.ts
packages/plugin-truffle/test/test/beacon-upgrade-block-proxy.js
packages/plugin-truffle/test/test/implementation-functions.js

Support prepareUpgrade from an implementation address

---

docs/modules/ROOT/pages/api-hardhat-upgrades.adoc
docs/modules/ROOT/pages/platform-deploy.adoc
packages/core/CHANGELOG.md
packages/core/package.json
packages/plugin-hardhat/CHANGELOG.md
packages/plugin-hardhat/package.json

- Add links in docs
- Reorganize functions in docs
- Add beta notices
- Bump versions

Prepare Platform deployments for release

---

packages/plugin-hardhat/CHANGELOG.md
packages/plugin-hardhat/src/index.ts
packages/plugin-hardhat/src/type-extensions.ts

Fixes https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/793

Fix platform hardhat type

---

LICENSE

Just noticed the outdated year in the License file.

Update LICENSE to 2023

---

scripts/bundle-pack.sh

This action might not be needed anymore, but fixing it for now.

Fix GitHub action

---

docs/modules/ROOT/pages/foundry/pages/foundry-defender.adoc

Update to use commit https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/commit/c50a7968d369f852607cb72e653d1ed699d823c5 for docs.

Update Foundry Upgrades submodule

---

docs/modules/ROOT/pages/foundry/api/pages/api-foundry-upgrades.adoc
docs/modules/ROOT/pages/foundry/pages/foundry-defender.adoc
docs/modules/ROOT/pages/foundry/pages/foundry-upgrades.adoc

Updates Foundry Upgrades submodule to commit https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/commit/7552dab50bff7d895da2b194e15774f2af91eb2a

Update Foundry Upgrades docs

---

docs/modules/ROOT/pages/foundry/api/pages/Options.adoc

Update docs for https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/pull/75
Related to #1076

Update Foundry Upgrades plugin docs

---

docs/modules/ROOT/pages/foundry/pages/foundry-upgrades.adoc

Related to https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/pull/91

Update docs for Foundry Upgrades to v0.4.0

---

packages/core/CHANGELOG.md
packages/core/src/provider.ts

Add Sonic network to manifest file names
