packages/plugin-buidler/README.md, packages/plugin-buidler/src/deploy-proxy.ts
Fixes #122.
Stores the deployment transaction in the contract instance. This is used by `await contract.deployed()` to wait until the deployment transaction is mined.
It was necessary to ignore a TypeScript error. This property is sometimes readonly ([example](https://github.com/ethers-io/ethers.js/blob/9640e864a68b4a9e84e820f0ceaf1eb56c66715f/packages/contracts/src.ts/index.ts#L1156)) but not in our case since we create the instance with [`attach`](https://github.com/ethers-io/ethers.js/blob/9640e864a68b4a9e84e820f0ceaf1eb56c66715f/packages/contracts/src.ts/index.ts#L1160-L1162).
=> Store deployTransaction in Ethers contract instances

packages/plugin-buidler/src/deploy-proxy.ts, packages/plugin-buidler/test.js, packages/plugin-buidler/test/contracts/Initializers.sol, packages/plugin-buidler/test/initializers.js
Fixes #146.
We were only allowing initializer names, which doesn't work with overloading. This PR changes the implementation to use the native [`Interface.getFunction`](https://docs.ethers.io/v5/api/utils/abi/interface/#Interface--fragments) function provided by Ethers, which supports all of: names, signatures, and selectors.
cc @abcoathup: This should be reflected in the API docs which I didn't edit in this PR because we moved them to another file in the `docs` branch (#142). See [Specifying Fragments](https://docs.ethers.io/v5/api/utils/abi/interface/#Interface--specifying-fragments) in the Ethers documentation for the different ways initializers can be specified.
=> Fix Buidler deployProxy for overloaded initializers

packages/plugin-buidler/README.md, packages/plugin-truffle/README.md
* Fixes links to the main `README.md` file from within the Plugin folders (both `/plugin-buidler` and `/plugin-truffle`.
=> fix: links to main README

packages/core/package.json, packages/plugin-buidler/package.json, packages/plugin-truffle/package.json
The repository currently doesn't show any dependents: https://github.com/OpenZeppelin/openzeppelin-upgrades/network/dependents
A project that has Upgrades Plugins as a dependency doesn't show links to the repository:
https://github.com/abcoathup/box/network/dependencies
Adding repository URI to each package.json in case this resolves the issue when the packages are next released.
=> Add repository URI to package.json

packages/core/CHANGELOG.md, packages/plugin-truffle/src/truffle.ts, packages/plugin-truffle/src/wrap-provider.ts
some parity settings check for jsonrpc  version and will  respond with invalid json rpc version error message if not set
=> fix: add jsonrpc version

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/api-hardhat-upgrades.adoc, docs/modules/ROOT/pages/hardhat-upgrades.adoc, docs/modules/ROOT/pages/index.adoc, docs/modules/ROOT/pages/migrate-from-cli.adoc, docs/modules/ROOT/pages/network-files.adoc, packages/plugin-hardhat/README.md
We have to update https://forum.openzeppelin.com/t/openzeppelin-upgrades-step-by-step-tutorial-for-buidler/3580 once this is released.
See also https://github.com/OpenZeppelin/docs.openzeppelin.com/pull/261.
=> Replace all Buidler mentions in documentation

packages/core/package.json, packages/core/scripts/copy-artifacts.sh, packages/core/src/validate.test.ts, packages/core/src/validate.ts
#206 introduced breaking changes that could've resulted in broken installations of `@openzeppelin/truffle-upgrades`. This PR introduces just a few lines that are enough to fix the backwards compatibility of `core/validate`, and a script that copies artifacts to their previous location.
=> Fix backwards compatibility of core@1.3.0

packages/plugin-hardhat/CHANGELOG.md, packages/plugin-hardhat/contracts/DeployOverload.sol, packages/plugin-hardhat/package.json, packages/plugin-hardhat/src/deploy-proxy.ts, packages/plugin-hardhat/test/deploy-overload.js, packages/plugin-truffle/CHANGELOG.md, packages/plugin-truffle/src/deploy-proxy.ts, packages/plugin-truffle/test/contracts/DeployOverload.sol, packages/plugin-truffle/test/test/deploy-overload.js
Adds an overload to `deployProxy` so that the options object can be specified as a second argument, omitting the empty args array.
A few people had issues because they assumed this was possible [[1]](https://forum.openzeppelin.com/t/types-values-length-mismatch/4613) [[2]](https://forum.openzeppelin.com/t/contract-is-not-upgrade-safe-defining-structs-is-not-yet-supported/4597).
=> Allow ommitting `args` in `deployProxy` when it's an empty array

docs/modules/ROOT/pages/writing-upgradeable.adoc
Example in documentation to not use initial values in field declarations was actually a constant, causing confusion.
Based on feedback in community forum: https://forum.openzeppelin.com/t/initial-value-in-upgrade-contract/4688/5?u=abcoathup
=> Clarify constant usage instead of Initial Values in Field Declarations

docs/modules/ROOT/pages/api-hardhat-upgrades.adoc, docs/modules/ROOT/pages/api-truffle-upgrades.adoc, packages/core/CHANGELOG.md, packages/core/src/validate.ts, packages/plugin-hardhat/CHANGELOG.md, packages/plugin-hardhat/src/index.ts, packages/plugin-hardhat/src/type-extensions.ts, packages/plugin-hardhat/test/happy-path-with-enums.js, packages/plugin-hardhat/test/happy-path-with-structs.js, packages/plugin-hardhat/test/linked-libraries.js, packages/plugin-truffle/CHANGELOG.md, packages/plugin-truffle/src/index.ts, packages/plugin-truffle/test.sh, packages/plugin-truffle/test/migrations/1_initial_migration.js
Fixes #226 
Requested by a user in the forum [[1]](https://forum.openzeppelin.com/t/logging-verbose-during-local-tests-with-upgradeable-contracts/4633). I think it makes sense.
=> Add a function to silence warnings

packages/core/CHANGELOG.md, packages/core/src/storage.ts, packages/plugin-hardhat/CHANGELOG.md, packages/plugin-hardhat/contracts/PortfolioV2.sol, packages/plugin-hardhat/test/happy-path-with-structs.js, packages/plugin-truffle/CHANGELOG.md, packages/plugin-truffle/test/contracts/PortfolioV2.sol, packages/plugin-truffle/test/test/happy-path-with-structs.js
The `unsafeAllowCustomTypes` flag was causing other storage layout incompatibilities to be ignored.
=> Fix error in unsafeAllowCustomTypes flag

docs/modules/ROOT/pages/faq.adoc, docs/modules/ROOT/pages/index.adoc, docs/modules/ROOT/pages/proxies.adoc, docs/modules/ROOT/pages/writing-upgradeable.adoc
Update docs to use OpenZeppelin Contracts Upgradeable `Intializable`
Remove reference to CLI docs for ProxyAdmin
Fix typos
=> Update docs for OpenZeppelin Contracts Upgradeable

packages/plugin-hardhat/CHANGELOG.md, packages/plugin-hardhat/src/admin.ts, packages/plugin-hardhat/src/index.ts, packages/plugin-hardhat/test/admin-instance.js, packages/plugin-truffle/CHANGELOG.md, packages/plugin-truffle/src/admin.ts, packages/plugin-truffle/test/test/admin-happy-path.js
This PR is for kicking off #173.
An `deployedProxyAdmin` method is added to `admin` module to get `ProxyAdmin` instance (feel free to suggest names). My use case is simply to get the address programmatically without `fs.readFileSync` the manifest.
=> Add admin.getInstance

packages/plugin-hardhat/contracts/Adder.sol, packages/plugin-hardhat/contracts/AdderV2.sol, packages/plugin-hardhat/contracts/ExternalLibraries.sol, packages/plugin-hardhat/contracts/Invalid.sol, packages/plugin-hardhat/contracts/InvalidGreeter.sol, packages/plugin-hardhat/contracts/Portfolio.sol, packages/plugin-hardhat/contracts/PortfolioV2.sol, packages/plugin-hardhat/contracts/Token.sol, packages/plugin-hardhat/contracts/TokenV2.sol, packages/plugin-truffle/test/contracts/Action.sol, packages/plugin-truffle/test/contracts/ActionV2.sol, packages/plugin-truffle/test/contracts/Adder.sol, packages/plugin-truffle/test/contracts/AdderV2.sol, packages/plugin-truffle/test/contracts/ExternalLibraries.sol, packages/plugin-truffle/test/contracts/Portfolio.sol, packages/plugin-truffle/test/contracts/PortfolioV2.sol, packages/plugin-truffle/test/contracts/Token.sol, packages/plugin-truffle/test/contracts/TokenV2.sol
This was left over from the initial days of the prototype doing manual testing. It is only adding noise in the console and not providing any value for the tests.
=> Remove console.log from test contracts

docs/modules/ROOT/pages/writing-upgradeable.adoc
In the latest version of "@openzeppelin/contracts-upgradeable" (v4.1.0 as of writing this), the "Initializable.sol" contract is located in a new "utils" sub-directory.
=> docs: fix typo in writing-upgradeable.adoc

packages/core/src/deployment.test.ts, packages/core/src/deployment.ts, packages/core/src/provider.test.ts, packages/core/src/provider.ts, packages/core/src/stub-provider.ts
If eth_getCode fails to return the code immediately after the tx is mined (which can happen when there is a reorg, or if the provider hits a different node behind a load balancer that has not received that tx yet, or on moonbase), the plugin would return invalid deployment. This change adds a 1-min polling to allow the provider to catch up.
=> Handle slow eth_getCode providers

packages/core/contracts/test/FunctionSignatures.sol, packages/core/src/utils/function.ts
Fix #405 
Function signature reconstruction did not support functions in the parameters, which caused errors to be thrown.
=> Support function objects in arguments

packages/plugin-truffle/package.json, yarn.lock
This PR updates the @truffle/contract dependency in order to work with newer truffle versions.
See [this issue for details](https://github.com/trufflesuite/truffle/issues/4183#issuecomment-888287945)
=> Bump @truffle/contract version

packages/plugin-hardhat/package.json, packages/plugin-truffle/package.json
These packages were implicitly pulling in chalk (via @openzeppelin/upgrades-core); this makes the dependency more explicit.
=> Add chalk to dependencies

packages/plugin-hardhat/src/deploy-beacon-proxy.ts, packages/plugin-hardhat/test/beacon-upgrade-block-proxy.js
Adds a check to `deployBeaconProxy()` to verify that the beaconAddress points to a beacon before deploying the beacon proxy.
=> Check address for beacon before deploying beacon proxy

packages/plugin-hardhat/src/utils/debug.ts, packages/plugin-hardhat/src/utils/deploy.ts
When using certain RPC endpoints with Polygon Mumbai, an incorrect contract address can be returned.  This causes the Hardhat plugin to write the wrong addresses to the manifest.
This occurs in:
https://forum.openzeppelin.com/t/error-no-contract-at-address-0x-removed-from-manifest/20609
https://forum.openzeppelin.com/t/invaliddeployment-error-no-contract-at-address-0x-removed-from-manifest/21383
As a workaround, calculate the correct address using the signer's address and the transaction nonce.
=> Override contract deployment address

README.md, docs/modules/ROOT/pages/hardhat-upgrades.adoc, docs/modules/ROOT/pages/index.adoc, packages/plugin-hardhat/README.md, packages/plugin-truffle/README.md
Identical to https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/497 but for the readmes to match the adocs from the other PR.  
Also fixed a few details in the adocs.
=> Update readmes to be consistent with adoc changes for beacon proxies

packages/core/CHANGELOG.md, packages/core/src/index.ts, packages/core/src/manifest.test.ts, packages/core/src/manifest.ts
I realized looking at a manifest that we're storing `admin.deployTransaction` with a bunch of data that we shouldn't have there. The admin deployment object wasn't being normalized to remove extra fields.
=> Fix normalization of admin in manifest

packages/plugin-hardhat/CHANGELOG.md, packages/plugin-hardhat/package.json, packages/plugin-hardhat/src/utils/validations.ts
Fixes #528 
Lockfile use was copied from Manifest.lock.
=> Use lockfile when reading validations.json

packages/plugin-hardhat/src/utils/validations.ts
Fixes https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/537
Change validations lock settings to have more retries and minimize unnecessary waits between retries:
- settings: retries 10, minimum timeout 50 ms, exponential backoff factor 1.3
- (previously was retries 3, minimum timeout 1000 ms, exponential backoff factor 2)
=> Use default number of retries, lower backoff factor

docs/modules/ROOT/pages/api-hardhat-upgrades.adoc, docs/modules/ROOT/pages/api-truffle-upgrades.adoc, packages/core/src/proxy-kind.ts, packages/plugin-hardhat/CHANGELOG.md, packages/plugin-hardhat/contracts/CustomProxy.sol, packages/plugin-hardhat/src/force-import.ts, packages/plugin-hardhat/test/import.js, packages/plugin-truffle/CHANGELOG.md, packages/plugin-truffle/src/force-import.ts, packages/plugin-truffle/test/contracts/CustomProxy.sol, packages/plugin-truffle/test/test/import.js
For https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/548
- Instead of detecting transparent/UUPS proxies kind based on admin storage slot, infer the kind through existence of `upgradeTo(address)` in the provided implementation contract instead.  This will allow UUPS proxies that have an admin to be properly imported as UUPS rather than transparent.
- Support optional `kind` to allow user to force the proxy kind to be uups, transparent, or beacon
=> Support importing UUPS proxy with admin

packages/plugin-truffle/CHANGELOG.md, packages/plugin-truffle/src/utils/debug.ts, packages/plugin-truffle/src/utils/validations.ts
Fixes https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/549
Related to https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3218
If an import looks like an OpenZeppelin interface that transitively imports an interface at a different path with the same file name, ignore the AST and allow processing to continue.
=> Ignore AST for imports that have the same name as dependency

packages/core/CHANGELOG.md, packages/core/src/validate/overrides.ts
Add `unsafeSkipStorageCheck` into `ValidationOptions` which was added in [@openzeppelin/hardhat-upgrades@1.16.0](https://github.com/OpenZeppelin/openzeppelin-upgrades/releases/tag/%40openzeppelin%2Fhardhat-upgrades%401.16.0)
=> Support unsafeSkipStorageCheck option in ValidationOptions

packages/core/src/index.ts, packages/plugin-defender-hardhat/src/propose-upgrade.ts, packages/plugin-defender-hardhat/test/propose-upgrade-uups.js
This PR makes the multisig property a required field when the user is making a proposal to upgrade a UUPS proxy
=> Defender Hardhat: Require multisig address when UUPS proxy 

packages/plugin-defender-hardhat/CHANGELOG.md, packages/plugin-defender-hardhat/package.json, yarn.lock
We got a support request via email with this error:
The issue was introduced [here](https://github.com/OpenZeppelin/openzeppelin-upgrades/commit/052a09900804fdb66be4deec7f19f1930b45487e#diff-8f628b53d0a150cddf2068194e438f596bb7091f5503d69c6a18a5ddc0ef0cfcR53), and seems like it has to be with the `@openzeppelin/hardhat-upgrades` version
=> Bump @openzeppelin/hardhat-upgrades in @openzeppelin/hardhat-defender

packages/core/CHANGELOG.md, packages/core/src/impl-address.ts
When using Gnosis Chain, `defender.proposeUpgrade` encounters this error in `isBeacon`
```
ProviderError: VM execution error.
at HttpProvider.request (/Users/.../DefenderUpgrade/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
at LocalAccountsProvider.request (/Users/.../DefenderUpgrade/node_modules/hardhat/src/internal/core/providers/accounts.ts:188:34)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at getImplementationAddressFromBeacon (/Users/.../node_modules/@openzeppelin/upgrades-core/src/impl-address.ts:30:25)
at isBeacon (/Users/.../node_modules/@openzeppelin/upgrades-core/src/beacon.ts:11:5)
at Proxy.proposeUpgrade (/Users/.../node_modules/@openzeppelin/hardhat-defender/src/propose-upgrade.ts:48:16)
at main …
```
=> Fix VM execution error when checking isBeacon

packages/plugin-hardhat/package.json, packages/plugin-truffle/package.json
`debug` is imported as a util and `ethers` is used directly in `plugin-hardhat`, so both of these should be declared as dependencies. I chose to declare `ethers` as a peerDependency to match `@nomiclabs/hardhat-ethers`.
=> plugins: Add missing debug and ethers dependencies

packages/plugin-hardhat/CHANGELOG.md, packages/plugin-hardhat/src/upgrade-proxy.ts, packages/plugin-truffle/CHANGELOG.md, packages/plugin-truffle/src/upgrade-proxy.ts
I am developing dApp on Klaytn network. (EVM Based)
The null address in the Klaytn network is contract, so a bytecode exists.
(You can see the code [here](https://scope.klaytn.com/account/0x0000000000000000000000000000000000000000?tabId=contractCode))
Therefore, with UUPS, I cannot upgrade the Implementation of the proxy.
The solution I thought of is to add a condition to make sure that adminAddress is null.
=> Add condition to use UUPS/Transparent if the adminAddress is zero in the getUpgrader func

docs/modules/ROOT/pages/api-hardhat-upgrades.adoc, docs/modules/ROOT/pages/api-truffle-upgrades.adoc
Adds a caution note to clarify that forceImport should be used with the current implementation contract version for a proxy/beacon, not the version that the user is planning to upgrade to.
=> Add caution note to forceImport doc

packages/core/CHANGELOG.md, packages/core/package.json
Fixes the following error in upgrades-core version 1.19.0:
```
Error: Cannot find module '@openzeppelin/upgrades-core/artifacts/@openzeppelin/contracts/proxy/transparent/ProxyAdmin.sol/ProxyAdmin.json'
```
=> Fix missing module

packages/plugin-defender-hardhat/src/index.ts, packages/plugin-defender-hardhat/src/propose-upgrade.ts, packages/plugin-defender-hardhat/src/utils.ts, packages/plugin-defender-hardhat/test/propose-upgrade-beacon.js, packages/plugin-defender-hardhat/test/propose-upgrade-transparent.js, packages/plugin-defender-hardhat/test/propose-upgrade-unsafeAllow.js, packages/plugin-defender-hardhat/test/propose-upgrade-use-deployed.js, packages/plugin-defender-hardhat/test/propose-upgrade-uups.js, packages/plugin-defender-hardhat/test/utils.js
Fixes #661
Example runs with no API secret set:
```
~/Projects/upgrades/examples/propose-upgrade-on-defender (master)$ yarn hardhat console --network rinkeby
yarn run v1.19.1
$ /home/spalladino/Projects/upgrades/node_modules/.bin/hardhat console --network rinkeby
Welcome to Node.js v14.20.0.
Type ".help" for more information.
> 
(To exit, press Ctrl+C again or Ctrl+D or type .exit)
> 
Done in 2.78s.
~/Projects/upgrades/examples/propose-upgrade-on-defender (master)$ yarn hardhat run scripts/transparent.js --network rinkeby
yarn run v1.19.1
$ /home/spalladino/Projects/upgrades/node_modules/.bin/hardhat run scripts/transparent.js --network rinkeby
Proposing upgrade to V2...
Defender API key and secret are not set. Add the following to your hardhat.config.js exported configuration:
{ …
```
=> Ignore unset Defender API key unless necessary

packages/core/CHANGELOG.md, packages/core/contracts/test/Storage089.sol, packages/core/src/storage-0.8.test.ts, packages/core/src/storage/compare.ts
Support contracts that have user defined value types, when there is not a storage layout. Truffle does not provide a storage layout so in order to support user defined value types we need to use the underlying type to compare between the original and the updated contract.
=> Use underlying value when storage layout is not available

docs/modules/ROOT/pages/api-core.adoc, packages/core/CHANGELOG.md, packages/core/contracts/test/ValidationsSameNameSafe.sol, packages/core/contracts/test/ValidationsSameNameUnsafe.sol, packages/core/src/manifest-storage-layout.test.ts, packages/core/src/standalone.test.ts, packages/core/src/validate.test.ts, packages/core/src/validate/data.ts, packages/core/src/validate/query.ts, packages/core/src/validate/run.ts, packages/plugin-hardhat/test/implementation-functions.js, packages/plugin-truffle/test/test/implementation-functions.js
Validations were stored as a map with the contract names as the keys.  However, there could be multiple contracts with the same name in different Solidity files, which can lead to the wrong contract being validated.  Instead, use fully qualified contract names (e.g. `path/file.sol:ContractName`) as the keys instead.
Fixes https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/263
=> Support multiple contracts with same name

packages/core/CHANGELOG.md, packages/core/src/storage/report.ts
Fixing small storage report error seen [in the forum](https://forum.openzeppelin.com/t/bad-storage-gap-resize/33668/5?u=frangio):
(Notice empty `>` line.)
=> Avoid printing empty hint

packages/plugin-hardhat/CHANGELOG.md, packages/plugin-hardhat/src/verify-proxy.ts
Currently the verify task can only verify
a beacon if a proxy for the beacon is already
deployed. This is not always the case, a proxy
for a beacon may get deployed long after the
beacon and implementation contracts. This change
makes `verify` compatible with the results of
`deployBeacon`.
=> Enable verify to verify beacons

packages/plugin-hardhat/src/verify-proxy.ts
https://github.com/blockscout/blockscout/blob/620178117fc008d0a926fb0c989864515f897487/apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/logs_controller.ex#L6-L22
blockscout will return `No logs found` error message if no logs for the request.
=> Handle getLogs error for blockscout explorer

packages/core/CHANGELOG.md, packages/core/src/validate/run.test.ts, packages/core/src/validate/run.ts
Fixes the case where
```
/**
* @custom:oz-upgrades-unsafe-allow constructor
*     @custom:oz-upgrades-unsafe-allow-reachable delegatecall
*/
```
gives an error:
```
NatSpec: oz-upgrades-unsafe-allow argument not recognized: @custom:oz-upgrades-unsafe-allow-reachable
```
=> Improve regex for unsafe-allow annotations

packages/core/CHANGELOG.md, packages/core/src/src-decoder.ts
See https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/713.
This does not fix the issue (I don't know what the issue is) but it properly catches the error instead of causing a TypeError and should give us the name of the file that's causing the issue.
=> Fix runtime type error on undefined source

packages/core/CHANGELOG.md, packages/core/src/validate/run.ts
Improves compilation performance by using global caches for delegatecall and selfdestruct opcodes during validations. 
Fixes LIB-648
=> Use global caches for opcode validations

docs/modules/ROOT/pages/api-core.adoc, docs/modules/ROOT/pages/api-hardhat-upgrades.adoc, docs/modules/ROOT/pages/api-truffle-upgrades.adoc
Document:
- Parameters (including options)
- Returns
- Since - the minimum package version required for each recent function, so that users know when they need to update their package.  This includes functions related to beacon proxy support, forceImport, granular functions, and Etherscan verification.
=> Document function params, options, returns, and since version

docs/modules/ROOT/pages/proxies.adoc
Replacing the obsolete link to the Solidity documentation (from version 0.6.12) with the **latest**.
=> Replacing the obsolete Solidity documentation link

packages/core/src/manifest.test.ts, packages/core/src/manifest.ts
If a Hardhat manifest file was found in the previous location as `unknown-31337.json`, allow migrating it to the new dev instance manifest location.
Related to https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/726
=> Enable migrating from previous Hardhat manifest location to dev instance manifest

packages/core/CHANGELOG.md, packages/core/src/provider.ts
And so avoid spurious "clashes" when upgrading proxy implementation contracts. Pull less hair.  👍 
Tested. Works now so much better.  😃
=> add Foundry's "anvil" as a "development network"

.eslintrc.js, packages/core/CHANGELOG.md, packages/core/hardhat.config.js, packages/core/hardhat/separate-test-contracts.js, packages/core/scripts/copy-build-info.js
Fixes #750
When compiling contracts in the `core` package, marks any contracts that are not part of `@openzeppelin/contracts/proxy` to be compiled separately.
Note that dependencies of `@openzeppelin/contracts/proxy` would still be compiled along with `@openzeppelin/contracts/proxy`
This results in the `build-info` file used for source code verification to only have the proxy contracts and their dependencies.
=> Remove test contracts from source code verification

packages/plugin-truffle/CHANGELOG.md, packages/plugin-truffle/src/deploy-beacon-proxy.ts, packages/plugin-truffle/src/deploy-proxy.ts, packages/plugin-truffle/src/upgrade-proxy.ts, packages/plugin-truffle/src/utils/truffle.ts, packages/plugin-truffle/test/migrations/2_1_deploy_greeter_transparent.js, packages/plugin-truffle/test/migrations/2_2_deploy_greeter_uups.js, packages/plugin-truffle/test/migrations/2_3_deploy_greeter_beacon.js
The implementation contract transactionHash is not set to the proxy contract transactionHash in the build/contracts/\<ContractName\>.json file.
build:
```
"networks": {
"5777": {
"events": {},
"links": {},
"address": "0xd6Fd7B733e189109Ba0874B8c886Cc509a1b2C85",
"transactionHash": "0xef8418e2bfea6f4175e86a707154ce63508d458c363074f3161fc92bdf4cd0ec"
}
},
```
.openzeppelin:
```
"proxies": [
{
"address": "0xd6Fd7B733e189109Ba0874B8c886Cc509a1b2C85",
"txHash": "0xea38585fa68592eec02faec61331e91d101be13bcdd54010bb8016a41d3ecde4",
"kind": "transparent"
}
],
"impls": {
"851eb7f66375439b9eb97824f366c9260c3472be98d739e29eccd0f291c5aaf9": {
"address": "0xBb2100DeA2AfE3fc661e625E6F6673ca36bF0198",
"txHash": "0xef8418e2bfea6f4175e86a707154ce63508d458c363074f3161fc92bdf4cd0ec",
...
}
}
```
=> Use proxy transactionHash for implementation contract abstraction in Truffle

docs/modules/ROOT/pages/api-hardhat-upgrades.adoc, docs/modules/ROOT/pages/api-truffle-upgrades.adoc
I think this line is left over from before we had `constructorArgs`.
=> Fix constructor docs

docs/modules/ROOT/pages/proxies.adoc
In the following page for the OpenZeppelin upgrade docs --> https://docs.openzeppelin.com/upgrades-plugins/1.x/proxies
The Solidity code snippet for the proxy forwarding (delegatecall in fallback function) does not work with the new solc version 0.8.x
The assembly opcodes now use the syntax with parentheses like `calldatasize()` for instance.
I am making this PR to update the docs.
Only part where I am not sure is for retrieving the address of the implementation contract from the contract state.
I use in assembly `sload(_impl.slot)` but maybe this is probably not robust because we don't know what else in the storage slot packed alongside the `_impl` address.
=> Update proxy fallback solidity code snippet for solc 0.8.0

docs/modules/ROOT/pages/api-hardhat-upgrades.adoc, packages/plugin-hardhat/CHANGELOG.md, packages/plugin-hardhat/src/admin.ts, packages/plugin-hardhat/test/transparent-change-admin-signer.js, packages/plugin-hardhat/test/transparent-change-admin-wrong-signer.js, packages/plugin-hardhat/test/transparent-transfer-admin-ownership-signer.js, packages/plugin-hardhat/test/transparent-transfer-admin-ownership-wrong-signer.js
Fixes #782 
Supports passing in an optional Signer parameter to `admin.changeProxyAdmin` and `admin.transferProxyAdminOwnership`
=> Allow custom signer for admin functions

docs/modules/ROOT/pages/writing-upgradeable.adoc
Related to https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/785
Double underscores were not being rendered correctly in the doc.
=> Escape underscores in storage gap doc

packages/core/CHANGELOG.md, packages/core/package.json, packages/plugin-hardhat/CHANGELOG.md, packages/plugin-hardhat/package.json, packages/plugin-hardhat/src/upgrade-proxy.ts, packages/plugin-hardhat/src/utils/factories.ts, packages/plugin-truffle/CHANGELOG.md, packages/plugin-truffle/package.json, packages/plugin-truffle/src/upgrade-proxy.ts, packages/plugin-truffle/src/utils/factories.ts, yarn.lock
Closes #774
Closes #773
Closes #772
Closes #771
Updates proxies in order to use updated [TransparentUpgradeableProxy](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4154) from [Contracts 4.8.3](https://github.com/OpenZeppelin/openzeppelin-contracts/releases/tag/v4.8.3).
Note: Using this version of the plugin to verify a proxy that was deployed by a previous version of the plugin will fail.  See https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/674 for details.  Users who are affected should downgrade the plugins to the previous version, run the verify task, then upgrade the plugins back to the latest version.
=> Use proxies from OpenZeppelin Contracts 4.8.3

packages/core/CHANGELOG.md, packages/core/package.json, packages/plugin-hardhat/CHANGELOG.md, packages/plugin-hardhat/package.json, packages/plugin-truffle/CHANGELOG.md, packages/plugin-truffle/package.json
https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/795 missing this interface file and cause compile error.
```
Error: Cannot find module '@openzeppelin/upgrades-core/artifacts/@openzeppelin/contracts/proxy/transparent/TransparentUpgradeableProxy.sol/ITransparentUpgradeableProxy.json'
```
=> Fix ITransparentUpgradeableProxy.json not found.

docs/modules/ROOT/pages/api-hardhat-upgrades.adoc, packages/plugin-hardhat/CHANGELOG.md, packages/plugin-hardhat/src/platform/deploy.ts, packages/plugin-hardhat/src/utils/options.ts, packages/plugin-hardhat/test/platform-deploy.js
When using Platform, deployments are performed using the CREATE2 opcode. This option allows users to provide the salt for the deployment. If not provided, Platform defaults to using a random salt.
=> Support `salt` option for deployments on OpenZeppelin Platform

README.md
As title. `ethers` defaults to the breaking v6 and `@nomiclabs/hardhat-ethers` already has released a RC version for `3.0.0`, so this is a preemptive measure. You should consider adding the peer deps also in the `package.json`.
=> Pin versioning for peer dependencies

docs/modules/ROOT/pages/faq.adoc
there's also a broken link in 
`this information to validate that your contracts are [upgrade safe](#what-does-it-mean-for-a-contract-to-be-upgrade-safe).` 
but I couldn't figure out why easily.
=> Fix typo and link in docs

packages/plugin-hardhat/CHANGELOG.md, packages/plugin-hardhat/src/utils/deploy.ts
Closes https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/767
Remove overriding the contract address on deployments, since ethers.js's `deploy` function already calculates the address for the create operation.
=> Remove address override

docs/modules/ROOT/pages/faq.adoc, packages/core/CHANGELOG.md, packages/core/contracts/test/ValidationsNatspec.sol, packages/core/src/validate/report.ts, packages/core/src/validate/run.ts
Assignment to immutable variables currently requires both overrides `state-variable-immutable` and `state-variable-assignment`. I believe the second one should be implicit. Assignment is a problem when it's in storage.
=> Allow assignment of immutable variables

packages/core/CHANGELOG.md, packages/core/contracts/test/Storage089.sol, packages/core/src/storage-0.8.test.ts, packages/core/src/utils/is-value-type.ts
This fixes the upgraded contract storage check failure when using a custom value types in mappings, e.g.
```
mapping(UserDefinedValueType => ...) mappingThatFails;
```
See https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/779#issuecomment-1527902368
I can confirm that this fixes the upgrade for a contract that uses such mapping (I'm using `upgradeProxy` from hardhat-upgrades).
cc @frangio who suggested the fix
=> Support user-defined value types in mappings

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/api-truffle-upgrades.adoc, docs/modules/ROOT/pages/truffle-upgrades.adoc, packages/plugin-truffle/README.md
Deprecate Truffle Upgrades due to https://consensys.io/blog/consensys-announces-the-sunset-of-truffle-and-ganache-and-new-hardhat
=> Add Truffle deprecation notices

packages/plugin-hardhat/CHANGELOG.md, packages/plugin-hardhat/src/force-import.ts, packages/plugin-hardhat/test/import-50.js, packages/plugin-hardhat/test/import.js
Fixes https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/882
When importing a proxy, the proxy kind can be inferred based on the presence of upgrade function signatures in the implementation.
For transparent proxies, we import the admin address using the admin address slot.  During this import, we check whether the admin address has code.
If the proxy kind was inferred incorrectly, or if the user provided the wrong `kind` option (e.g. passed in 'transparent' but the proxy is actually UUPS), the admin address is the zero address.  This causes the error when we check for code at the admin address:
```
No contract at address 0x0000000000000000000000000000000000000000 (Removed from manifest)
```
Instead, we should throw an error if the admin address is zero, and tell the user to set …
=> Check for non-zero admin address when importing transparent proxy

packages/plugin-hardhat/CHANGELOG.md, packages/plugin-hardhat/package.json, packages/plugin-hardhat/src/defender/deploy.ts, packages/plugin-hardhat/src/defender/get-default-approval-process.ts, packages/plugin-hardhat/src/defender/propose-upgrade-with-approval.ts, packages/plugin-hardhat/src/defender/utils.ts, packages/plugin-hardhat/test/defender-deploy.js, packages/plugin-hardhat/test/defender-get-default-approval-process.js, packages/plugin-hardhat/test/defender-utils.js, packages/plugin-hardhat/test/propose-upgrade-with-approval-beacon.js, packages/plugin-hardhat/test/propose-upgrade-with-approval-transparent.js, packages/plugin-hardhat/test/propose-upgrade-with-approval-unsafeAllow.js, packages/plugin-hardhat/test/propose-upgrade-with-approval-use-deployed.js, packages/plugin-hardhat/test/propose-upgrade-with-approval-uups.js, yarn.lock
=> Update Defender deployments to use Defender SDK

packages/core/ava.config.js, packages/plugin-hardhat/ava.config.js
Tests when running coverage currently fails for two reasons:
- CLI tests in core may take longer than the default timeout of 10 seconds -> increase timeout
- Console output has color, so does not match snapshots -> remove color
=> Fix tests when running coverage

.github/workflows/checks.yml, packages/plugin-hardhat/CHANGELOG.md, packages/plugin-hardhat/package.json, packages/plugin-hardhat/src/defender-v1/propose-upgrade.ts, packages/plugin-hardhat/src/defender/deploy.ts, packages/plugin-hardhat/tsconfig.json, yarn.lock
=> Update Defender SDK

packages/core/CHANGELOG.md, packages/core/package.json, packages/plugin-hardhat/CHANGELOG.md, packages/plugin-hardhat/package.json, yarn.lock
- Update peer dependency on `@nomicfoundation/hardhat-verify` to ^2.0.0
- hardhat-verify v2 supports Sourcify.  We don't support Sourcify yet, but we override `verify:etherscan` so there is no impact since Sourcify is part of a different code path. 
- Merge from master
- Remove alpha version tags
- Update changelogs
=> Prepare hardhat-upgrades v3 for release

packages/core/CHANGELOG.md, packages/core/src/impl-store.test.ts, packages/core/src/impl-store.ts
Avoids checking for address clash when using `forceImport` or `redeployImplementation: 'always'`.
Address clashes should not occur in general, because it indicates a deployment is being attempted to an address which was already in the manifest, and such deployment should not occur if the bytecode version hash was the same before (unless using `forceImport` or `redeployImplementation: 'always'`, which triggers a deployment regardless of an existing bytecode version hash).  
Fixes #938
=> Avoid address clash when redeploying implementation

packages/core/CHANGELOG.md, packages/core/src/manifest.test.ts, packages/core/src/manifest.ts, packages/core/src/provider.ts
When handling network manifest files, we use the [RPC method `hardhat_metadata`](https://hardhat.org/hardhat-network/docs/reference#hardhat_metadata) to determine if the connected network is a Hardhat development network, in which case we write the manifest to the temp dir instead of `.openzeppelin`.
Furthermore, if this method has a `forkedNetwork` field in its response, we treat this as a network fork and make a copy of the origin networks's manifest file, so that we can write to it for the fork without affecting the original version.
In recent versions of Anvil, Anvil also supports the `hardhat_metadata` RPC method, but has `"forkedNetwork": null` in its response as seen [here](https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/943#issuecomment-1864052578).
This PR does two …
=> Fix manifest error when connecting to an Anvil dev network

packages/plugin-hardhat/CHANGELOG.md, packages/plugin-hardhat/src/utils/etherscan-api.ts
When attempting to verify contracts on Snowtrace, I received the following error:
`Etherscan returned with message: NOTOK, reason: Invalid querystring request`
Looking at the Etherscan API I noticed that all endpoints used query parameters instead of a form-encoded body like in the code. With this change my verification calls are now working.
It's not clear to me why the original implementation was created or how it's working on Etherscan - I assume that Snowtrace conforms closer to the API spec and that is why the change is required.
=> Use query instead of body for Etherscan API

packages/core/CHANGELOG.md, packages/core/src/cli/validate/build-info-file.test.ts, packages/core/src/cli/validate/build-info-file.ts
This PR addresses 2 issues:
1. When running validations from CLI, we previously looked for the following `outputSelection` from the build info file, and gave an error if that was missing:
```
outputSelection: {
'*': {
'*': ['storageLayout']
}
}
```
However, in recent versions of Foundry (reported in https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/issues/4), running `forge script` no longer uses the above format.  Instead, it has settings enabled for each individual contract, like:
```
outputSelection: {
'mypath/MyContract.sol': {
'': ['ast'],
'*': ['abi', 'evm.bytecode', 'evm.deployedBytecode', 'evm.methodIdentifiers', 'metadata', 'storageLayout']
}
}
```
This PR checks each contract's settings and gives an error if any of them do not have `storageLayout`.
2. Additionally, …
=> CLI: Improve checks for build info file settings

packages/core/CHANGELOG.md, packages/core/src/manifest.ts
Fixes #962 
Network files can be in several locations:
1. The fallback location if the network is not known: `.openzeppelin/unknown-<chain id>.json`
2. A named location based on the network name (for live networks) such as `.openzeppelin/<network name>.json`
3. Within the temp directory (e.g. `/tmp/openzeppelin-upgrades/hardhat-31337-<hardhat instance id>.json`) if using a dev network such as Hardhat or Anvil.
If the file exists in (1) the fallback location (from a previous run of the Upgrades plugins), and a newer version of the plugin is aware of and wants to use (2) or (3), it tries to move it from (1) to (2) or (3).
To allow this move to occur across filesystems, we should copy and delete it instead of directly renaming it.
=> Enable moving network file across filesystems

docs/modules/ROOT/pages/api-hardhat-upgrades.adoc, packages/plugin-hardhat/src/defender/deploy.ts, packages/plugin-hardhat/test/defender-deploy.js
Fixes #923 
The Hardhat Upgrades plugin typically expects address and txHash to be available immediately after submitting a deployment.
For Defender deployments using Relayers, these are available.
For Defender deployments using EOA or Safe, these are only available when the deployment completes.  This PR checks if these are not available, in which case we prompt to tell the user to submit the deployment in Defender and waits until these are available.
Also updates `salt` option documentation based on [this information](https://docs.openzeppelin.com/defender/v2/tutorial/deploy#deploy-caveat)
=> Support Defender deployments using EOA or Safe

docs/modules/ROOT/pages/api-hardhat-upgrades.adoc, packages/plugin-hardhat/CHANGELOG.md, packages/plugin-hardhat/package.json, packages/plugin-hardhat/src/admin.ts, packages/plugin-hardhat/test/transparent-v4-transfer-admin-ownership-multiple.js
Fixes issue reported in https://forum.openzeppelin.com/t/openzeppelin-hardhat-upgrades-s-admin-transferproxyadminownership-always-logs-success/39686
transferProxyAdminOwnership previously iterated through all proxies from the manifest file, and displayed either:
```
console.log(SUCCESS_CHECK + `${address} (${kind}) proxy ownership transferred through proxy admin`);
```
or
```
console.log(FAILURE_CROSS + `${address} (${kind}) proxy ownership not affected by proxy admin`);
```
to help the user see which proxies were using that proxy admin.  This was useful with proxies from OpenZeppelin Contracts 4.x because the plugin only tracked 1 proxy admin and all transparent proxies were using the same admin.
But with OpenZeppelin Contracts 5.x where each proxy deploys its own proxy admin, this is …
=> Remove console logging for transferProxyAdminOwnership

docs/modules/ROOT/pages/foundry/pages/foundry-defender.adoc, docs/modules/ROOT/pages/foundry/pages/foundry-upgrades.adoc
Update Foundry Upgrades submodule to https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/releases/tag/v0.2.1
=> Update Foundry Upgrades submodule to v0.2.1

docs/modules/ROOT/pages/network-files.adoc, packages/core/src/manifest.ts
For a repo that uses multiple environments deploying to the same networks, static MANIFEST_DEFAULT_DIR set to .openzeppelin is not enough.
I know it's simple way of handling it via environment variable but I haven't seen in the repo best way to make such changes.
If this is not preferred way, please let me know and I will update this PR with changes
Fixes https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/672
❤️
=> chore: add possibility of changing default MANIFEST_DEFAULT_DIR with env variable

packages/plugin-hardhat/CHANGELOG.md, packages/plugin-hardhat/contracts/Constructor.sol, packages/plugin-hardhat/package.json, packages/plugin-hardhat/src/defender/deploy.ts, packages/plugin-hardhat/test/defender-deploy.js
Fixes #1026 
Defender deployments are run using the internal `defenderDeploy` function, which takes constructor arguments directly using the `...args` argument.  This function can deploy proxies or implementations.
However, users may provide `constructorArgs` to specify constructor args for the implementation contract.  These should not apply to the proxy deployment itself.
Therefore, the internal `defenderDeploy` function should use its `args` to override the ones in `opts.constructorArgs`, so that the correct arguments are used for each specific deployment.
=> Defender: Fix proxy deployments when using `constructorArgs`

packages/core/CHANGELOG.md, packages/core/package.json, packages/core/src/utils/make-namespaced.ts
Fixes #1074 
Slang supports specific Solidity versions, currently up to `0.8.26`.  If the user's project is using `0.8.27`, this causes error `Unsupported language version '0.8.27'`
As a longer-term solution, we may want to try falling back to the most recent version supported by Slang for parsing, but we should evaluate the implications of that further.
For now, we just skip the Slang code path (i.e. we won't remove non-struct NatSpec) for solc versions not supported by Slang.
=> Skip Slang parser for solc versions that it does not support

docs/modules/ROOT/pages/foundry/api/pages/Options.adoc, docs/modules/ROOT/pages/foundry/api/pages/api-foundry-upgrades.adoc, docs/modules/ROOT/pages/foundry/pages/foundry-upgrades.adoc
Update submodule and regenerate docs
=> Update docs from Foundry Upgrades

docs/antora.yml, docs/modules/ROOT/pages/api-hardhat-upgrades.adoc
Upgrades Plugins docs are for the latest versions of the plugins and includes information about previous versions where appropriate.
Its current link shows https://docs.openzeppelin.com/upgrades-plugins/1.x/ but the `1.x` is irrelevant.  This PR changes it to have no version according to https://docs.antora.org/antora/latest/component-with-no-version/
Afterwards, we can add a redirect in https://github.com/OpenZeppelin/docs.openzeppelin.com/pull/423 in case anyone is still using the old link.
=> Remove version from Upgrades Plugins docs url

docs/modules/ROOT/pages/foundry/pages/foundry-upgrades.adoc
Updates to include https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/pull/88
=> Update Foundry docs for URL changes

LICENSE, packages/plugin-hardhat/CHANGELOG.md, packages/plugin-hardhat/package.json, packages/plugin-hardhat/src/defender/deploy.ts, packages/plugin-hardhat/test/defender-deploy.js, yarn.lock
- Upgrades `defender-sdk` dependency to v2.1.0
- Introduces `origin` to defender deployment requests (hardcoded to "Hardhat") for improving usage tracking across different Defender clients
=> feat: upgrade defender-sdk deps + add origin property to deployments

packages/core/CHANGELOG.md, packages/core/contracts/test/ValidationsInitializer.sol, packages/core/package.json, packages/core/src/validate-initializers.test.ts, packages/core/src/validate/run/initializer.ts
Referenced AST ids can be negative if they refer to nodes that are not in the solc output.  For example, `require` statements seem to have referenced AST ids of `-18`.
When validating initializers, we should ignore negative AST id references.
Fixes #1116
=> Fix `ASTDereferencerError` when validating initializers

.github/workflows/checks.yml, .gitmodules, package.json, scripts/check-diff-docs.sh, scripts/prepare-foundry-docs.sh
The workflow if trigger externally from `openzeppelin-foundry-upgrades` CI if changes were detected to the docs.
It updates the submodule, re-genrate the documentation, if changes are confirmed on the generated documentation creates a new branch, commit and push the changes then a pull request is open from this branch to the main branch (it creating the pull request fails the created branch is deleted).
Additionally the checking difference during preparing (copying) the docs from the submodule to the root got decoupled so that having differences does not fail the CI as the changes will be committed in the pull request.
=> Create action workflow to get latest docs changes from openzeppelin-foundry-upgrades

packages/core/CHANGELOG.md, packages/core/package.json, packages/core/src/validate/run.ts, packages/core/src/validate/run/initializer.ts
Background:
When checking for issues in parent initializer calls according to https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/1095, we recursively check initializer functions and the functions that they call.
When an function calls a built-in function, the referenced AST node ID of the built in function may be negative (which was fixed in https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/1116), or it could be represented as a large positive number as reported in #1128.
We previously only ignored negative numbers, but since there is no way to conclusively identify that a large positive number is negative, we should also ignore when the referenced function node ID is not found.
---
Testing:
I tested that this works by temporarily removing the checks for negative node …
=> Ignore function node IDs not found when validating parent initializer calls

docs/modules/ROOT/pages/writing-upgradeable.adoc, packages/core/CHANGELOG.md, packages/core/contracts/test/ValidationsInitializer.sol, packages/core/package.json, packages/core/src/validate-initializers.test.ts, packages/core/src/validate/run/initializer.ts
- Adds a section in docs about the initializer validations that are performed by Upgrades Plugins.
- Logs a note when reinitializers are detected, to tell users that reinitializers are not included in validations by default.
- Support a custom NatSpec annotation `@custom:oz-upgrades-validate-as-initializer` to mark arbitrary functions to be treated as initializers for validations.
- This can be used for any function that is not normally detected as an initializer (for example, custom initializer functions that do not use `onlyInitializing` or `initializer` modifiers), and can also be used on reinitializers to include them in validations.
Fixes https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/1122
Related to https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/1125
=> Support annotation to validate arbitrary functions as initializers

docs/modules/ROOT/pages/defender-deploy.adoc, docs/modules/ROOT/pages/foundry/pages/foundry-defender.adoc
This PR addresses the issue described in #996 by clarifying that the API keys referenced in the Defender integration documentation are specifically from the Production or Test Deploy Environment that was configured in Defender.
- Updated `defender-deploy.adoc` to add a note explaining that the API keys are specifically from the Deploy Environment
- Updated `foundry-defender.adoc` to clarify that the API keys are from the Deploy Environment
- Added links to the Defender tutorial's environment setup documentation in both files
Closes #996
=> docs: clarify Defender Deploy Environment API keys
